add sunset to prayers
batoulapps/adhan-js pull request #107
Opened 2022-05-10 20:08 UTC by jd1378

closes  #105 
since it was remained open, I thought maybe create a pull request

2022-05-10 20:25 UTC, z3bi requested changes

2022-05-10 20:25 UTC, z3bi commented on Adhan.d.ts
> +  Sunset,
we can add sunset to the PrayerTimes object but I don't want to change the `Prayer` enum.

2022-05-10 20:25 UTC, z3bi commented on src/Prayer.js
> +    Sunset: 'sunset',
Should be removed as we are not changing this.

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        const sunsetAdjustment = (calculationParameters.adjustments.sunset || 0) + (calculationParameters.methodAdjustments.sunset || 0);
i thought the point was to expose the true sunset value, why would we add adjustments?

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        else if (prayer === Prayer.Sunset) {
remove

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        this.sunset = roundedMinute(dateByAddingMinutes(sunsetTime, sunsetAdjustment), calculationParameters.rounding);
we should remove the call to `dateByAddingMinutes` and only do the rounding to preserve true sunset time.

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        else if (date >= this.sunset && this.sunset !== this.maghrib) {
remove

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        else if (date >= this.sunset) {
revert

2022-05-10 20:25 UTC, z3bi commented on src/PrayerTimes.js
> +        else if (date >= this.asr && this.sunset !== this.maghrib) {
remove

2022-05-11 12:34 UTC, jd1378 commented
is it okay now ?

2022-05-11 13:39 UTC, sgtsquiggs commented
This pull requests needs to be against the develop branch, which is in typescript instead of javascript.

2022-05-11 14:04 UTC, closed without merging